import {authenticate,login} from "./auth.js";
import {handleUsers} from "./users.js";
import {respondToCase,responseDefinition} from "./responses.js";
import {handleFollowups} from "./followups.js";
const ORIGIN="https://newcityvip.github.io", cors=o=>o===ORIGIN?{"Access-Control-Allow-Origin":o,Vary:"Origin"}:{}, json=(d,s=200,o)=>Response.json(d,{status:s,headers:{"Cache-Control":"no-store",...cors(o)}}), okid=v=>/^\d+$/.test(String(v))&&Number(v)>0;
const safeCase=r=>({id:r.id,status:r.status,received_at:r.received_at,shop_code:r.shop_code,raw_message:r.raw_message,matched_rule_id:r.matched_rule_id,matched_rule_name:r.matched_rule_name,assigned_user_id:r.assigned_user_id,assigned_agent_display_name:r.assigned_agent_display_name,assigned_at:r.assigned_at,answered_at:r.answered_at,closed_at:r.closed_at,created_at:r.created_at,updated_at:r.updated_at});
const safeResponse=r=>({id:r.id,case_id:r.case_id,user_id:r.user_id,response_type:r.response_type,response_text:r.response_text,telegram_response_message_id:r.telegram_response_message_id,status:r.status,error_message:r.error_message,created_at:r.created_at,sent_at:r.sent_at});
async function summary(db,u){const own=u.role==="AGENT"?" WHERE assigned_user_id=?":"",a=u.role==="AGENT"?[u.id]:[],r=await db.prepare(`SELECT status,COUNT(*) count FROM cases${own} GROUP BY status`).bind(...a).all(),st=Object.fromEntries(r.results.map(x=>[x.status,x.count])),base={ok:true,scope:u.role==="AGENT"?"SELF":"GLOBAL",total_cases:r.results.reduce((n,x)=>n+x.count,0),open:st.OPEN||0,statuses:st};if(u.role==="AGENT")return base;const e=await db.batch([db.prepare("SELECT COUNT(*) count FROM users WHERE is_active=1 AND role='AGENT'"),db.prepare("SELECT COUNT(*) count FROM shop_assignments WHERE is_active=1")]);return{...base,unassigned:st.UNASSIGNED||0,answered:st.ANSWERED||0,closed:st.CLOSED||0,active_agents:e[0].results[0].count,active_shop_assignments:e[1].results[0].count};}
async function listCases(db,u,p){const w=[],v=[];if(u.role==="AGENT"){w.push("c.assigned_user_id=?");v.push(u.id);}for(const[k,c]of[["status","c.status"],["shop_code","c.shop_code"],["assigned_user_id","c.assigned_user_id"]]){const x=p.get(k)?.trim();if(!x)continue;if(k==="assigned_user_id"&&(u.role!=="ADMIN"||!okid(x)))return{error:"INVALID_FILTER",status:400};w.push(`${c}=?`);v.push(k==="assigned_user_id"?Number(x):x.toUpperCase());}const r=await db.prepare(`SELECT c.*,r.rule_name matched_rule_name,u.display_name assigned_agent_display_name FROM cases c LEFT JOIN rules r ON r.id=c.matched_rule_id LEFT JOIN users u ON u.id=c.assigned_user_id ${w.length?`WHERE ${w.join(" AND ")}`:""} ORDER BY c.id DESC LIMIT 100`).bind(...v).all();return{ok:true,cases:r.results.map(safeCase)};}
async function detail(db,u,id){const a=u.role==="AGENT"?[id,u.id]:[id],r=await db.prepare(`SELECT c.*,r.rule_name matched_rule_name,r.response_type configured_response_type,r.response_config configured_response_config,dg.group_name destination_group_name,u.display_name assigned_agent_display_name FROM cases c LEFT JOIN rules r ON r.id=c.matched_rule_id LEFT JOIN telegram_groups dg ON dg.id=r.destination_group_id LEFT JOIN users u ON u.id=c.assigned_user_id WHERE c.id=?${u.role==="AGENT"?" AND c.assigned_user_id=?":""}`).bind(...a).first();if(!r)return{error:"CASE_NOT_FOUND",status:404};const cols=await db.prepare("PRAGMA table_info(responses)").all(),has=cols.results.some(x=>x.name==="case_id"),x=await db.batch([db.prepare("SELECT case_id,telegram_chat_id,telegram_message_id,message_type,message_text FROM case_messages WHERE case_id=?").bind(id),db.prepare("SELECT * FROM audit_logs WHERE case_id=? ORDER BY id").bind(id),...(has?[db.prepare("SELECT * FROM responses WHERE case_id=? ORDER BY id").bind(id)]:[])]);return{ok:true,case:safeCase(r),response_definition:responseDefinition(r.configured_response_type,r.configured_response_config),destination_group_name:u.role==="ADMIN"?r.destination_group_name||null:undefined,case_messages:x[0].results,audit_logs:x[1].results,responses:has?x[2].results.map(safeResponse):[],responses_available:has,warnings:has?[]:["Response history unavailable"]};}
async function assign(req,db,u,id){if(u.role!=="ADMIN")return{error:"FORBIDDEN",status:403};let b;try{b=await req.json();}catch{return{error:"INVALID_JSON",status:400};}if(!okid(b?.user_id))return{error:"INVALID_USER_ID",status:400};const now=new Date().toISOString(),x=await db.batch([db.prepare(`INSERT INTO audit_logs(user_id,case_id,action,entity_type,entity_id,old_value,new_value,metadata) SELECT ?,id,CASE WHEN assigned_user_id IS NULL THEN 'CASE_MANUALLY_ASSIGNED' ELSE 'CASE_REASSIGNED' END,'CASE',CAST(id AS TEXT),json_object('assigned_user_id',assigned_user_id,'assigned_at',assigned_at,'status',status),json_object('assigned_user_id',?,'assigned_at',?,'status',CASE WHEN status='UNASSIGNED' THEN 'OPEN' ELSE status END),json_object('source','PORTAL') FROM cases WHERE id=? AND EXISTS(SELECT 1 FROM users WHERE id=? AND is_active=1 AND role='AGENT')`).bind(u.id,b.user_id,now,id,b.user_id),db.prepare("UPDATE cases SET assigned_user_id=?,assigned_at=?,status=CASE WHEN status='UNASSIGNED' THEN 'OPEN' ELSE status END WHERE id=? AND EXISTS(SELECT 1 FROM users WHERE id=? AND is_active=1 AND role='AGENT')").bind(b.user_id,now,id,b.user_id)]);return x[1].meta.changes?{ok:true}:{error:"CASE_OR_AGENT_NOT_FOUND",status:404};}
const bool=v=>v===true||v===false?v:typeof v==="string"&&/^(true|false)$/i.test(v.trim())?v.trim().toLowerCase()==="true":null;
async function sync(env,u){
  if(u.role!=="ADMIN")return{error:"FORBIDDEN",status:403};
  if(!env.GSHEET_SYNC_URL||!env.GSHEET_SYNC_SECRET)return{error:"SYNC_NOT_CONFIGURED",status:503};
  const url=new URL(env.GSHEET_SYNC_URL);url.searchParams.set("key",env.GSHEET_SYNC_SECRET);
  const q=await fetch(url),p=await q.json(),hasGroups=Object.prototype.hasOwnProperty.call(p||{},"groups");
  if(!q.ok||p?.ok!==true||!Array.isArray(p.assignments)||(hasGroups&&!Array.isArray(p.groups)))return{error:"INVALID_SYNC_SOURCE",status:502};
  const errors=[],seen=new Set(),want=[];
  for(const[i,r]of p.assignments.entries()){
    const shop=String(r.shop_code??r.Shop_Code??"").trim().toUpperCase(),name=String(r.agent_username??r.Agent_Username??"").trim(),active=bool(r.active??r.Active);
    if(!shop)errors.push({row:i+2,error:"SHOP_CODE_REQUIRED"});if(seen.has(shop))errors.push({row:i+2,error:"DUPLICATE_SHOP_CODE"});seen.add(shop);
    if(active===null)errors.push({row:i+2,error:"INVALID_ACTIVE"});if(active&&!name)errors.push({row:i+2,error:"AGENT_USERNAME_REQUIRED"});want.push({shop,name,active});
  }
  const groups=[],seenGroups=new Set();
  if(hasGroups)for(const[i,r]of p.groups.entries()){
    const group=typeof r?.shop_group==="string"?r.shop_group.trim().toUpperCase():"",chat=typeof r?.chat_id==="string"?r.chat_id.trim():"",tag=typeof r?.telegram_tag==="string"?r.telegram_tag.trim():"";
    if(!group)errors.push({dataset:"groups",row:i+2,error:"SHOP_GROUP_REQUIRED"});if(seenGroups.has(group))errors.push({dataset:"groups",row:i+2,error:"DUPLICATE_SHOP_GROUP"});seenGroups.add(group);
    if(!chat)errors.push({dataset:"groups",row:i+2,error:"CHAT_ID_REQUIRED"});if(!tag)errors.push({dataset:"groups",row:i+2,error:"TELEGRAM_TAG_REQUIRED"});else if(!/^@[A-Za-z0-9_]{5,32}$/.test(tag))errors.push({dataset:"groups",row:i+2,error:"INVALID_TELEGRAM_TAG"});
    groups.push({group,chat,tag});
  }
  const users=(await env.DB.prepare("SELECT id,username,role,is_active FROM users").all()).results,byUser=new Map(users.map(x=>[x.username,x]));
  for(const[i,d]of want.entries())if(d.active){d.user=byUser.get(d.name);if(!d.user)errors.push({row:i+2,error:"UNKNOWN_AGENT"});else if(!d.user.is_active)errors.push({row:i+2,error:"INACTIVE_AGENT"});else if(d.user.role!=="AGENT")errors.push({row:i+2,error:"AGENT_ROLE_REQUIRED"});}
  if(errors.length)return{error:"VALIDATION_FAILED",errors,status:422};
  const old=(await env.DB.prepare("SELECT * FROM shop_assignments").all()).results,map=new Map(old.map(x=>[x.shop_code.toUpperCase(),x])),stmts=[];let inserted=0,updated=0,deactivated=0,unchanged=0;
  for(const d of want){const x=map.get(d.shop);map.delete(d.shop);if(d.active&&!x){inserted++;stmts.push(env.DB.prepare("INSERT INTO shop_assignments(shop_code,assigned_user_id,is_active,updated_at) VALUES(?,?,1,CURRENT_TIMESTAMP)").bind(d.shop,d.user.id));}else if(x&&d.active&&(x.assigned_user_id!==d.user.id||!x.is_active)){updated++;stmts.push(env.DB.prepare("UPDATE shop_assignments SET assigned_user_id=?,is_active=1,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(d.user.id,x.id));}else if(x&&!d.active&&x.is_active){deactivated++;stmts.push(env.DB.prepare("UPDATE shop_assignments SET is_active=0,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(x.id));}else unchanged++;}
  for(const x of map.values())if(x.is_active){deactivated++;stmts.push(env.DB.prepare("UPDATE shop_assignments SET is_active=0,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(x.id));}else unchanged++;
  const groupCounts={inserted:0,updated:0,deactivated:0,unchanged:0};
  if(hasGroups){const oldGroups=(await env.DB.prepare("SELECT * FROM followup_groups").all()).results,groupMap=new Map(oldGroups.map(x=>[x.shop_group.toUpperCase(),x]));for(const d of groups){const x=groupMap.get(d.group);groupMap.delete(d.group);if(!x){groupCounts.inserted++;stmts.push(env.DB.prepare("INSERT INTO followup_groups(shop_group,telegram_chat_id,telegram_tag,is_active,updated_at) VALUES(?,?,?,1,CURRENT_TIMESTAMP)").bind(d.group,d.chat,d.tag));}else if(x.telegram_chat_id!==d.chat||x.telegram_tag!==d.tag||!x.is_active){groupCounts.updated++;stmts.push(env.DB.prepare("UPDATE followup_groups SET telegram_chat_id=?,telegram_tag=?,is_active=1,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(d.chat,d.tag,x.id));}else groupCounts.unchanged++;}for(const x of groupMap.values())if(x.is_active){groupCounts.deactivated++;stmts.push(env.DB.prepare("UPDATE followup_groups SET is_active=0,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(x.id));}else groupCounts.unchanged++;}
  if(stmts.length)await env.DB.batch(stmts);
  return{ok:true,inserted,updated,deactivated,unchanged,errors:[],groups:groupCounts};
}
export async function handleOperations(req,env,url=new URL(req.url)){const path=url.pathname,o=req.headers.get("Origin");if(path==="/dashboard"||path==="/dashboard/")return Response.redirect("https://newcityvip.github.io/telegram-ops/",302);if(!path.startsWith("/api/"))return null;if(o&&o!==ORIGIN)return json({ok:false,error:"ORIGIN_NOT_ALLOWED"},403);if(req.method==="OPTIONS")return new Response(null,{status:204,headers:{...cors(o),"Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Allow-Headers":"Authorization, Content-Type"}});try{if(path==="/api/auth/login"){const r=req.method==="POST"?await login(req,env):null;return r?json({ok:true,...r},200,o):json({ok:false,error:req.method==="POST"?"INVALID_CREDENTIALS":"METHOD_NOT_ALLOWED"},req.method==="POST"?401:405,o);}const userRoute=path==="/api/admin/users"||path.startsWith("/api/admin/users/"),followupRoute=path==="/api/followup-groups"||path==="/api/followup-requests"||path.startsWith("/api/followup-requests/"),write=path.endsWith("/assign")||path.endsWith("/respond")||path==="/api/admin/sync-shop-assignments"||(userRoute&&req.method==="POST")||(path==="/api/followup-requests"&&req.method==="POST");if(!followupRoute&&((write&&req.method!=="POST")||(!write&&req.method!=="GET")))return json({ok:false,error:"METHOD_NOT_ALLOWED"},405,o);const u=await authenticate(req,env);if(!u)return json({ok:false,error:"UNAUTHORIZED"},401,o);let r;if(path==="/api/auth/session")r={ok:true,user:u};else if(followupRoute)r=await handleFollowups(req,env,u,path);else if(userRoute)r=await handleUsers(req,env,u,path);else if(path==="/api/dashboard/summary")r=await summary(env.DB,u);else if(path==="/api/cases")r=await listCases(env.DB,u,url.searchParams);else if(path==="/api/agents")r=u.role==="ADMIN"?{ok:true,agents:(await env.DB.prepare("SELECT id,username,display_name,role,is_active FROM users WHERE is_active=1 AND role='AGENT'").all()).results}:{error:"FORBIDDEN",status:403};else if(path==="/api/shop-assignments")r=u.role==="ADMIN"?{ok:true,shop_assignments:(await env.DB.prepare("SELECT sa.*,u.display_name agent_display_name FROM shop_assignments sa LEFT JOIN users u ON u.id=sa.assigned_user_id ORDER BY sa.shop_code").all()).results}:{error:"FORBIDDEN",status:403};else if(path==="/api/admin/sync-shop-assignments")r=await sync(env,u);else{const m=path.match(/^\/api\/cases\/(\d+)(\/(assign|respond))?$/);r=m?(m[3]==="assign"?await assign(req,env.DB,u,+m[1]):m[3]==="respond"?await respondToCase(req,env,u,+m[1]):await detail(env.DB,u,+m[1])):{error:"NOT_FOUND",status:404};}return json(r,r.status||200,o);}catch(e){console.error("Operations API failed:",e);return json({ok:false,error:"OPERATIONS_FAILED"},500,o);}}
